### PR TITLE
Fix #1120 - rework how the use list prefix is determined.

### LINKED ISSUE #1120: reorder-imports panics if first line is use-statement in submodules
for the code `mod foo {use bar;}`, rustfmt panics with
```
thread 'main' panicked at 'Request to format inverted span: Loc { file: FileMap(stdin), line: 1, col: CharPos(9) } to Loc { file: FileMap(stdin), line: 1, col: CharPos(8) }', src/missed_spans.rs:50
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

This is not the same issue as #1111 , which was fixed.

### PR DESCRIPTION
**Pull request by studoot**
This fixes #1120, by ensuring that the start of the prefix before a list of `use` declarations cannot be before the last character processed by the formatter.

The prefix is also trimmed when we can detect that it ends with the indent whitespace of a `use` declaration within a block.

### CODE REVIEW

File: tests/target/issue-1120.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// rustfmt-reorder_imports: true
```
Comment (nrc) [inline tests/target/issue-1120.rs]: Could you add a comment to the test explaining what is being tested please?

Does this exercise the new code around indents? If not could you add a test for that

**Comment by studoot** [comment]
I think that the new code around indents is exercised through the idempotence test for `tests/target/issue-1120.rs`. Without that part of the change, an extra line containing just whitespace was added when that file was formatted. However, I have added another item to the test file to cover that, verifying that indentation is correctly removed & reapplied.

**Comment by nrc** [comment]
Cool, looks good, thanks for the fix!
