### PR TITLE
Fix imports with absolute paths

### LINKED ISSUE #1051: `use ::{A, B}` turns into `use ::::{A, B}`
Formatting `use ::{A, B}` results in `use ::::{A, B}` (which is invalid).

### PR DESCRIPTION
**Pull request by julienXX**
Closes #1051

### CODE REVIEW

**Comment by nrc** [comment]
Thanks for the PR! That was very quick. I wonder if we could modify `types::rewrite_path` to return an empty string for an empty path, rather than special casing the logic for imports. That might not work, in which case this PR looks fine, but it would be good to try.

**Comment by julienXX** [comment]
Yes that would be nice, I'll look into it.

**Comment by julienXX** [comment]
@nrc I tried to return an empty string if the path is empty but then the leading `::` of the absolute path are removed. I'm not sure where it happens. Can you point me in the right direction?

File: src/imports.rs [hunk 1]
```diff
@@ -55,6 +55,8 @@ fn rewrite_single_use_list(path_str: String, vpi: &ast::PathListItem) -> String
         // A name.
         if path_str.is_empty() {
```
Comment (nrc) [inline src/imports.rs]: I guess if you are returning an empty path string, then you are hitting this path. So, we are not distinguishing between `::foo` and `foo`. I think the solution is not to branch on whether the path_str is empty (which could be due to either case) but change path_str to Option<String> where it is None for `foo` and Some("") for `::foo` (and it will need a comment explaining that).

**Comment by julienXX** [comment]
@nrc Thank to your help on IRC I updated the PR, are my comments understandable enough? Also I'm not sure the `path_str.clone()` approach I took is the best choice here.

**Comment by nrc** [comment]
@julienXX - sorry I missed your last commit - GitHub does not send a notification on a new commit, so I didn't see that you had fixed the problem. Would you mind rebasing the branch and then I can merge. Thank you!

**Comment by julienXX** [comment]
@nrc cool! The branch is now rebased.

**Comment by nrc** [comment]
Thank you!
