### PR TITLE
Make `is_mod_decl` more accommodating

### LINKED ISSUE #2403: rustfmt panic in version 0.3.7
```
$ rustfmt -V
0.3.7-nightly ( )

$ rustc +nightly -V
rustc 1.25.0-nightly (8ccab7eed 2018-01-31)

$ echo "mod a;" | RUST_BACKTRACE=1 rustfmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <syntax::codemap::CodeMap as rustfmt_nightly::codemap::SpanUtils>::span_after
  11: rustfmt_nightly::visitor::FmtVisitor::visit_item
  12: rustfmt_nightly::visitor::FmtVisitor::walk_items
  13: rustfmt_nightly::run
  14: rustfmt::execute
  15: rustfmt::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  19: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  20: main
  21: __libc_start_main
  22: _start
```

### PR DESCRIPTION
**Pull request by nrc**
Fixes #2403 (I think)

r? @topecongiro 

`is_mod_decl` was introduced for the re-ordering modules PR. I think the removed clause is bogus if we are formatting a program passed as a string rather than a file since in that case we have the 0s for `mod foo;`. Simply removing the clause seemed to pass tests, but I'm not sure if you had some use case in mind?

### CODE REVIEW

File: src/visitor.rs [hunk 1]
```diff
@@ -44,10 +44,7 @@ pub fn filter_inline_attrs(attrs: &[ast::Attribute], outer_span: Span) -> Vec<as
 /// Returns true for `mod foo;`, false for `mod foo { .. }`.
 fn is_mod_decl(item: &ast::Item) -> bool {
     match item.node {
-        ast::ItemKind::Mod(ref m) => {
-            !(m.inner.lo() == BytePos(0) && m.inner.hi() == BytePos(0))
-                && m.inner.hi() != item.span.hi()
-        }
+        ast::ItemKind::Mod(ref m) => m.inner.hi() != item.span.hi(),
```
Comment (nrc) [inline src/visitor.rs]: Hmm, I don't actually think this works at all - I think this condition is always false - for out of line mods the outer span ends at the `;` and the inner span ends at the end of the mod file. For inline mods the outer span includes the `}` but the inner span does not. I think we have to stick with the old method of looking at filenames, but that does mean we can't share the code for module reordering as easily.

Comment (topecongiro) [reply src/visitor.rs]: Actually for inline mods the inner span does include `}`. In ast.rs, it says:

```rust
/// Module declaration.
///
/// E.g. `mod foo;` or `mod foo { .. }`
#[derive(Clone, PartialEq, Eq, RustcEncodable, RustcDecodable, Hash, Debug)]
pub struct Mod {
    /// A span from the first token past `{` to the last token until `}`.
    /// For `mod foo;`, the inner span ranges from the first token
    /// to the last token in the external file.
    pub inner: Span,
    pub items: Vec<P<Item>>,
}
```

Comment (nrc) [reply src/visitor.rs]: Hmm, I interpreted that comment to mean it did not include the `}`, and it is weird to include the `{` but not the `}`. However, the parser does seem to include the `}`.
