### PR TITLE
Prevent conversion of empty tuples to unit structs

### LINKED ISSUE #1408: Format removes empty tuples from Impl but not from enum
I had something like

```rust
use std::convert::Into;

/// Known paths
pub enum Paths<'a> {
    Batch(),
    Buckets(),
    Bucket(&'a str)
}

impl<'a> Into<String> for Paths<'a> {
    fn into(self) -> String {
        match self {
            Paths::Batch() => format!("/batch"),
            Paths::Buckets() => format!("/buckets"),
            Paths::Bucket(id) => format!("/buckets/{id}", id = id),
        }
    }
}
```

After running format, it removed the empty tuples from the implementation match but not from the the enum definition. Leading to some errors. You can see the format result and the compiler output. 

```rust
use std::convert::Into;

/// Known paths
pub enum Paths<'a> {
    Batch(),
    Buckets(),
    Bucket(&'a str)
}

impl<'a> Into<String> for Paths<'a> {
    fn into(self) -> String {
        match self {
            Paths::Batch => format!("/batch"),
            Paths::Buckets => format!("/buckets"),
            Paths::Bucket(id) => format!("/buckets/{id}", id = id),
        }
    }
}
```
```
gsurita-30820:kinto-http.rs gsurita$ RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test 
   Compiling kinto_http v0.1.0 (file:///Users/gsurita/kinto-http.rs)
error[E0532]: expected unit struct/variant or constant, found tuple variant `Paths::Batch`
  --> src/paths.rs:21:13
   |
21 |             Paths::Batch => format!("/batch"),
   |             ^^^^^^^^^^^^ not a unit struct/variant or constant

error[E0532]: expected unit struct/variant or constant, found tuple variant `Paths::Buckets`
  --> src/paths.rs:22:13
   |
22 |             Paths::Buckets => format!("/buckets"),
   |             ^^^^^^^^^^^^^^ not a unit struct/variant or constant
```

### PR DESCRIPTION
**Pull request by alobb**
Fixes #1408

### CODE REVIEW

**Comment by nrc** [comment]
Thanks for the PRs! It's late on Saturday here, so I can't give a decent review, but I'll try and get to them tomorrow.

File: src/patterns.rs [hunk 1]
```diff
@@ -259,56 +259,52 @@ fn rewrite_tuple_pat(pats: &[ptr::P<ast::Pat>],
         pat_vec.insert(pos, dotdot);
     }
 
-    if pat_vec.is_empty() {
-        path_str
```
Comment (nrc) [inline src/patterns.rs]: While this is (I think) correct, it also seems inefficient. We could still keep the early return here, we just need to check whether we need `()` or not. However, I confess that I don't see how the code is working for the unit variant case - it looks to me like `TestEnum::Arm2` should get converted to `TestEnum::Arm2()`

Comment (alobb) [inline src/patterns.rs]: That sounds good, I'll look into adding back the early return.

As for why the unit variant case doesn't get the parens added, I think it returns early from the `try_opt` at [pattern:83](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/patterns.rs#L83), which means that it never enters [`rewrite_tuple_pat`](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/patterns.rs#L235), and instead does formatting in [`rewrite_path`](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/types.rs#L37).

Comment (nrc) [inline src/patterns.rs]: The way all the `try_opt`s work in rustfmt is that most rewrite functions return an `Option<String>`. If they successfully rewrite, they return the result in a `Some`, if they cannot rewrite in the space provided, then they return `None`. A small number of functions will try harder by making more space if one of their calless return `None`, but most just fail themselves. So if we are hitting an early return there, it basically means we are formatting at all (rustfmt has a fail-safe mechanism where if we don't format a node, we return the original text - that might be what is happening here. Obviously it is better if we don't do that).

Comment (alobb) [inline src/patterns.rs]: I may have been incorrect; looking at the AST generated by

```rust
enum TestEnum {
    Arm1(),
    Arm2,
}


fn main() {
    let test = TestEnum::Arm2;
    match test {
        TestEnum::Arm1 => {}
        TestEnum::Arm2 => {}
    }
}
```
[ast.txt](https://github.com/rust-lang-nursery/rustfmt/files/871021/ast.txt),

Arm2 isn't a tuple struct at all, but rather, a path, so that would explain why it doesn't have parens added

Comment (alobb) [inline src/patterns.rs]: What part of the else case is inefficient and should be avoided? It looks to me like any attempt to keep the early return will need duplication of a significant amount of code contained within the else case due to the possibility of `..`.

Comment (nrc) [inline src/patterns.rs]: I think that if pat_vec is empty, then there can be no `..`

Comment (nrc) [inline src/patterns.rs]: > Arm2 isn't a tuple struct at all, but rather, a path,

This suggests that the fix could be jsut adding `()` in the empty `pat_vec` case

Comment (alobb) [inline src/patterns.rs]: Yup, that worked; I thought I had tried this before, but had inadvertently moved the check to the beginning of the function, which meant it failed on tuples with only `..`.

**Comment by nrc** [comment]
Great, thanks!
