### PR TITLE
Do not scale WidthHeuristics when max_width less than 100

### LINKED ISSUE #2644: rustfmt breaks short lines when max_width is less than 100
When max_width is set to 80, lines that are shorter than 80 characters and would not be broken up with the default settings are broken up. For example with the default 100 characters I get
```rust
fn foo(e: Enum) {
    match e {
        Enum::Var { element1, element2 } => {
            return;
        }
    }
}
```
But with max_width set to 80, I get
```rust
fn foo(e: Enum) {
    match e {
        Enum::Var {
            element1,
            element2,
        } => {
            return;
        }
    }
}
```
I think the reasoning behind that is that if users want narrower lines, give them narrower blocks too. But I really don't think that is good reasoning. If I use a max width of 80, it's not because I want to have more lines, but because I want my lines to fit in 80 characters. I still want my lines to be as close to 80 characters as possible without hurting readability, and in this example, the first case reads better than the second.

Are there any users who actually expect blocks to be narrower as well when using an 80 maximum? If anything, I would expect 80 characters to be more old-terminal-friendly, where you would actually like less lines, not more lines, as long as the lines fit within the limit.

### PR DESCRIPTION
**Pull request by tspiteri**
Fixes #2644.

### CODE REVIEW

File: src/config/options.rs [hunk 1]
```diff
@@ -241,8 +241,14 @@ impl WidthHeuristics {
     }
     // scale the default WidthHeuristics according to max_width
     pub fn scaled(max_width: usize) -> WidthHeuristics {
-        let mut max_width_ratio: f32 = max_width as f32 / 100.0; // 100 is the default width -> default ratio is 1
-        max_width_ratio = (max_width_ratio * 10.0).round() / 10.0; // round to the closest 0.1
+        // 100 is the default width -> default ratio is 1
+        let max_width_ratio = if max_width > 100 {
```
Comment (nrc) [inline src/config/options.rs]: COuld we pull the default max width out into a const?

**Comment by tspiteri** [comment]
I added the `DEFAULT_MAX_WIDTH` constant in the function, added a test for the issue in commit 2, and added a test to check that width heuristics work for larger widths in commit 3. In commit 3 I also had to touch *config_type.rs* to make sure `self.set_heuristics()` is called if `max_width` changes, otherwise `WidthHeuristics` are not updated properly for the test's `rustfmt-max_width`.

**Comment by nrc** [comment]
Thank you, looks great!
