### PR TITLE
Use an explicit flag to decide on whether to add brace compensation for block expression

### LINKED ISSUE #2207: Closure with unsafe block and long function call panicks.
Code:
```rust
fn main() {
    a.map(|_| unsafe { a_very_long_function_name_or_anything_else() }.to_string())
}
```
Output:
```
thread 'main' panicked at 'Request to format inverted span: Loc { file: FileMap(/home/user/lol.rs), line: 2, col: CharPos(15), col_display: 15 } to Loc { file: FileMap(/home/user/lol.rs), line: 2, col: CharPos(14), col_display: 14 }', src/missed_spans.rs:68:8
```
Output with backtrace:
```
thread 'main' panicked at 'Request to format inverted span: Loc { file: FileMap(/home/user/lol.rs), line: 2, col: CharPos(15), col_display: 15 } to Loc { file: FileMap(/home/user/lol.rs), line: 2, col: CharPos(14), col_display: 14 }', src/missed_spans.rs:68:8
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17haba1b8b7cf61bd7aE.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h7be06c8634f460d7E.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hb62cac1b1e3c5e79E.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::format_missing_with_indent
   8: rustfmt_nightly::visitor::FmtVisitor::push_rewrite
   9: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  10: rustfmt_nightly::visitor::FmtVisitor::visit_block
  11: rustfmt_nightly::expr::rewrite_block_with_visitor
  12: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Block>::rewrite
  13: rustfmt_nightly::closures::rewrite_closure_block
  14: rustfmt_nightly::closures::rewrite_closure_with_block
  15: rustfmt_nightly::expr::format_expr
  16: rustfmt_nightly::closures::rewrite_last_closure
  17: rustfmt_nightly::expr::rewrite_last_arg_with_overflow
  18: rustfmt_nightly::expr::try_overflow_last_arg
  19: rustfmt_nightly::expr::rewrite_call_inner
  20: rustfmt_nightly::expr::rewrite_call
  21: rustfmt_nightly::chains::rewrite_chain_subexpr
  22: rustfmt_nightly::chains::rewrite_chain::{{closure}}
  23: rustfmt_nightly::chains::rewrite_chain
  24: rustfmt_nightly::expr::format_expr
  25: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  26: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  27: rustfmt_nightly::visitor::FmtVisitor::visit_block
  28: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  29: rustfmt_nightly::visitor::FmtVisitor::visit_item
  30: rustfmt_nightly::visitor::FmtVisitor::walk_items
  31: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  32: rustfmt_nightly::format_ast
  33: rustfmt_nightly::run
  34: rustfmt::execute
  35: rustfmt::main
  36: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  37: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  38: __libc_start_main
  39: <unknown>
```

Tested on latest master branch (`0.2.16-nightly (426ba1c 2017-11-28)`)

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2207.

### CODE REVIEW

File: src/visitor.rs [hunk 1]
```diff
@@ -90,17 +90,20 @@ impl<'a> FmtVisitor<'a> {
         }
     }
 
-    pub fn visit_block(&mut self, b: &ast::Block, inner_attrs: Option<&[ast::Attribute]>) {
+    pub fn visit_block(
+        &mut self,
+        b: &ast::Block,
+        inner_attrs: Option<&[ast::Attribute]>,
+        is_dummy: bool,
```
Comment (nrc) [inline src/visitor.rs]: COuld we call `is_dummy` `has_braces` or something similar? It's not obvious to me what `is_dummy` means.

Comment (topecongiro) [reply src/visitor.rs]: Thanks for the review!

`is_dummy` is `true` when we manually construct a block for the body of closure. Since the block is not present in the original code I called it dummy.
I agree that using `has_braces` is better, it is more natural to use a flag that is `true` most of the time and `false` in a narrow case. And the name is clearer.

**Comment by nrc** [comment]
Thanks!
