### PR TITLE
Fix off by 2 error in function sigs

### LINKED ISSUE #1000: off by one error with long type signatures
e.g.,
```
pub fn check_path<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
                            path: &hir::Path,
                            id: ast::NodeId,
                            cb: &mut FnMut(DefId, Span, &Option<&Stability>, &Option<Deprecation>)) {
```
The last line is 101 chars long, we should split it onto multiple lines.

### PR DESCRIPTION
**Pull request by nrc**
Fixes #1000

This is a little conservative in some cases, but better than being wrong in others.

### CODE REVIEW

File: src/items.rs [hunk 1]
```diff
@@ -1628,23 +1628,24 @@ fn compute_budgets_for_args(context: &RewriteContext,
...
     let new_indent = indent.block_indent(context.config);
-    let used_space = new_indent.width() + 2; // account for `(` and `)`
+    let used_space = new_indent.width() + 4; // Account for `(` and `)` and possibly ` {`.
     let max_space = context.config.max_width;
     if used_space <= max_space {
-        (0, max_space - used_space, new_indent)
+        Some((0, max_space - used_space, new_indent))
     } else {
         // Whoops! bankrupt.
         // FIXME: take evasive action, perhaps kill the indent or something.
```
Comment (marcusklaas) [inline src/items.rs]: This FIXME can be removed now, right?

**Comment by marcusklaas** [comment]
r+ with or without nit addressed
