### PR TITLE
Format comments with different opening in different manner

### LINKED ISSUE #691: Incorrect comment reformat
```
 //! `std` or `core` and simply link to this library. In case the target platform has no hardware
 //! support for some operation, software implementations provided by this library will be used
 //! automagically.
-// TODO: provide instructions to override default libm link and how to link to this library.
+//! TODO: provide instructions to override default libm link and how to link to this library.
```

### PR DESCRIPTION
**Pull request by topecongiro**
This PR closes #691.
However, TBH I am not sure whether how I deal with this issue is ideal.
Introducing `enum CommentStyle` seems overkill after looking back this PR.
I really appreciate any feedbacks.
Thank you in advance!

### CODE REVIEW

File: src/comment.rs [hunk 1]
```diff
@@ -47,39 +159,44 @@ pub fn rewrite_comment(orig: &str,
...
+    let rest = orig.lines()
+        .skip(first_group.lines().count())
+        .collect::<Vec<_>>()
+        .join("\n");
+
+    let first_group_str = try_opt!(rewrite_comment_inner(&first_group, block_style, shape, config));
+    if rest.is_empty() {
+        Some(first_group_str)
+    } else {
+        rewrite_comment(&rest, block_style, shape, config).map(|rest_str| {
```
Comment (nrc) [inline src/comment.rs]: Rather than have `rewrite_comment` and `rewrite_comment_inner` where the latter recurses, could we have a `rewrite_comment` function which calls an `identify_comment` where `identify_comment` is recursive?

**Comment by topecongiro** [comment]
Thank you! Rebased reflecting the feedbacks.
1. renamed `to_pattern` to `line_with_same_comment_style`.
2. created `identify_comment` and made it recursive.

File: src/comment.rs [hunk 2]
```diff
@@ -47,39 +163,52 @@ pub fn rewrite_comment(orig: &str,
...
+}
+
+fn identify_comment(orig: &str,
+                    block_style: bool,
+                    shape: Shape,
+                    config: &Config)
+                    -> Option<String> {
+    let style = comment_style(orig, false);
+    let first_group = orig.lines()
+        .take_while(|l| style.line_with_same_comment_style(l, orig, false))
```
Comment (topecongiro) [inline src/comment.rs]: I was wondering if rust has a function equivalent to [`scan`](http://hackage.haskell.org/package/base-4.9.1.0/docs/Prelude.html#v:span) in haskell.

Comment (nrc) [inline src/comment.rs]: I don't think there is one - there might be one in Itertools, but I prefer not to link it and use simpler functions.

Comment (nrc) [inline src/comment.rs]: You might be able to use [partition](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.partition)

**Comment by nrc** [comment]
Thanks for the changes!
