### PR TITLE
Print error and usage when decoding config file failed

### LINKED ISSUE #1426: chain_indent parsing crashes on 0.8.1
I just upgraded from 0.8.0 to 0.8.1 and found that a working config now crashes on `cargo fmt` without good info.

Here's the rustfmt.toml:

```toml
chain_base_indent = "tabbed"
chain_indent = "tabbed"
fn_arg_indent = "tabbed"
closure_block_indent_threshold = 0
single_line_if_else_max_width = 90
write_mode = "overwrite"
use_try_shorthand = true
```

OUTPUT:

```sh
Warning: Unused configuration option chain_base_indent
Warning: Unused configuration option fn_arg_indent
Decoding config file failed. Config:
chain_base_indent = "tabbed"
chain_indent = "tabbed"
fn_arg_indent = "tabbed"
closure_block_indent_threshold = 0
single_line_if_else_max_width = 90
write_mode = "overwrite"
use_try_shorthand = true



Parsed:
Table({"chain_base_indent": String("tabbed"), "chain_indent": String("tabbed"), "closure_block_indent_threshold": Integer(0), "fn_arg_indent": String("tabbed"), "single_line_if_else_max_width": Integer(90), "use_try_shorthand": Boolean(true), "write_mode": String("overwrite")})
thread 'main' panicked at 'explicit panic', /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-0.8.1/src/config.rs:319
stack backtrace:
   1:     0x562c7934661c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x562c79348fde - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x562c79348be4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x562c7934941b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x562c79105f0f - std::panicking::begin_panic::h20af3f49d5862a29
   6:     0x562c791ab1a6 - rustfmt::config::Config::from_toml::h694c4e7d25a2fc6a
   7:     0x562c790ed090 - rustfmt::resolve_config::h99bbe5e6dd9bf8f1
   8:     0x562c790f0528 - rustfmt::execute::h2a56a4ab73659311
   9:     0x562c790f24da - rustfmt::main::h1183d24b6d57d4a5
  10:     0x562c793502aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x562c79349b86 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  12:     0x7fb9165f4290 - __libc_start_main
  13:     0x562c790eae99 - _start
  14:                0x0 - <unknown>
```

This is on `rustc 1.16.0 (30cf806ef 2017-03-10)`

After some bisecting of the config it appears that the `chain_indent = "tabbed"` is what causes the crash, but that's not really identifiable by the crash.

Edit: fixed a typo.

### PR DESCRIPTION
**Pull request by topecongiro**
This commit changes the behavior of rustfmt to use default config when it failed to parse a config file.
Presumably closes #1426, but I am not sure if this is the preferable way to solve the issue.
I would appreciate feedback. Thank you!

### CODE REVIEW

**Comment by nrc** [comment]
Thanks for the PR. This is a reasonable fix, however, I think that alerting the user and not formatting is probably a better response. My reasoning is that this usually happens due to a typo in the config file, so the user wants to format in a non-standard way, but they make a typo, and end up here. I think it is better to tell the user that there toml file is broken, then they can fix it and try again. If we just carry on, then they don't get an immediate message, they may have to wait for formatting to finish (this can be slow on a large project and/or older computer), and probably we end up formatting with parameters that the user doesn't really want (which is why they're using the rustfmt.toml in the first place).

**Comment by topecongiro** [comment]
@nrc Thanks for your feedback. I feel that your reasoning makes much more sense than my PR.
I will try something like changing the return type of  `from_toml()` from `Config` to `Result<Config>`.

**Comment by topecongiro** [comment]
The new PR does the following:
1. Change the return type of `from_toml()` from `Config` to `Result<Config>`
2. Replace `expect()` with `try!` in `rustfmt.rs` to avoid panicking.

After this PR, the output will be like the following:
```
Warning: Unknown configuration option `chain_base_indent`
Warning: Unknown configuration option `fn_arg_indent`
Error: Decoding config file failed. Please check your config file.

usage: rustfmt [options] <file>...

Options:
    -h, --help          show this message
    -V, --version       show version information
    -v, --verbose       print verbose output
        --write-mode [replace|overwrite|display|diff|coverage|checkstyle]
                        mode to write in (not usable when piping from stdin)
        --skip-children 
                        don't reformat child modules
        --config-help   show details of rustfmt configuration options
        --config-path [Path for the configuration file]
                        Recursively searches the given path for the
                        rustfmt.toml config file. If not found reverts to the
                        input file path
        --file-lines JSON
                        Format specified line ranges. See README for more
                        detail on the JSON format.
```

File: src/bin/rustfmt.rs [hunk 1]
```diff
@@ -211,8 +214,8 @@ fn execute(opts: &Options) -> FmtResult<Summary> {
         }
         Operation::Stdin { input, config_path } => {
             // try to read config from local directory
-            let (mut config, _) = match_cli_path_or_file(config_path, &env::current_dir().unwrap())
-                .expect("Error resolving config");
+            let (mut config, _) =
+                try!(match_cli_path_or_file(config_path, &env::current_dir().unwrap()))
```
Comment (nrc) [inline src/bin/rustfmt.rs]: Prefer using `?` to `try!`

File: src/bin/rustfmt.rs [hunk 2]
```diff
@@ -232,8 +235,7 @@ fn execute(opts: &Options) -> FmtResult<Summary> {
             let mut path = None;
             // Load the config path file if provided
             if let Some(config_file) = config_path {
-                let (cfg_tmp, path_tmp) = resolve_config(config_file.as_ref())
-                    .expect(&format!("Error resolving config for {:?}", config_file));
+                let (cfg_tmp, path_tmp) = try!(resolve_config(config_file.as_ref()));
```
Comment (nrc) [inline src/bin/rustfmt.rs]: and here

File: src/bin/rustfmt.rs [hunk 3]
```diff
@@ -248,8 +250,7 @@ fn execute(opts: &Options) -> FmtResult<Summary> {
             for file in files {
                 // Check the file directory if the config-path could not be read or not provided
                 if path.is_none() {
-                    let (config_tmp, path_tmp) = resolve_config(file.parent().unwrap())
-                        .expect(&format!("Error resolving config for {}", file.display()));
+                    let (config_tmp, path_tmp) = try!(resolve_config(file.parent().unwrap()));
```
Comment (nrc) [inline src/bin/rustfmt.rs]: and here

**Comment by nrc** [comment]
Tests are failing because this doesn't seem to compile

**Comment by topecongiro** [comment]
@nrc Thanks! I will rebase shortly.
