### PR TITLE
Trim unnecessary whitespaces between a macro call and a semicolon

### LINKED ISSUE #2727: Can't properly format semicolon on new line
Adding new lines before the semicolon in the default hello world program like so:-

```rust
fn main() {
    println!("Hello, world!")
        
        
        
;
}
```

and running `cargo fmt` gives:-

```bash
internal error: left behind trailing whitespace
 --> /tmp/hello/src/main.rs:3
  |
3 |
  | ^^^^^^^^
internal error: left behind trailing whitespace
 --> /tmp/hello/src/main.rs:4
  |
4 |
  | ^^^^^^^^
internal error: left behind trailing whitespace
 --> /tmp/hello/src/main.rs:5
  |
5 |
  | ^^^^^^^^
warning: rustfmt may have failed to format. See previous 3 errors.
```

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2727.

### CODE REVIEW

File: src/missed_spans.rs [hunk 1]
```diff
@@ -46,6 +46,13 @@ impl<'a> FmtVisitor<'a> {
     // TODO these format_missing methods are ugly. Refactor and add unit tests
     // for the central whitespace stripping loop.
     pub fn format_missing(&mut self, end: BytePos) {
+        // HACK
```
Comment (nrc) [inline src/missed_spans.rs]: Could you copy the commit message here please so that we know more about the HACK in the code?

**Comment by topecongiro** [comment]
Thanks for the review, addressed the comment.
