### PR TITLE
Fix #1255 - incorrect removal of `default` on associated types

### LINKED ISSUE #1255: Default annotation incorrectly removed on associated types
Similar to #945. Occurs when formatting e.g. code equivalent to the following:
```
#![feature(specialization)]

trait Trait {
    type Type;
}
impl<T> Trait for T {
    default type Type = u64;
}
```
The default annotation on Type in the generic implementation of Trait disappears, even though it is meaningful and correct in that position.

### PR DESCRIPTION
**Pull request by gypsydave5**
This is a fix for issue #1255, and it's pretty much my first PR of any consequence, in Rust or any language, so I think I'd like to explain myself and what I've done.

Taking a look over the code (and taking a read of the Rust `ast`), I realised that `rustfmt` was treating `TraitItems` and `ImplItems` in the same way - passing them both over to `rewrite_associated_type`, which ignores the additional `defaultness` field on the impl item (hence the bug).

So I wrote a new function, `rewrite_associated_impl_type` (is this name right?), which can take the `defaultness` as an additional argument. This doesn't do anything more that prepend the result of the original function with `default` when appropriate.

I've covered this with an idempotence test - named with the issue number.

I'm sure this is far from perfect -- I'd really appreciate any feedback at all and I'm more than happy to commit some more time to this fix.

### CODE REVIEW

File: tests/target/issue_1255.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#![feature(specialization)]
+
+trait Trait {
+    type Type;
+}
+impl<T> Trait for T {
+    default type Type = u64;
+}
```
Comment (nrc) [inline tests/target/issue_1255.rs]: These files are slightly different in that the source version has a terminating newline but the target one does not. That may cause problems in the future.

However, if you want just an idempotence test, then you don't need the source version at, just a target file is necessary.

Could you add a comment to the file to explain what it being tested please?

File: src/items.rs [hunk 2]
```diff
@@ -1240,11 +1240,55 @@ pub fn rewrite_associated_type(ident: ast::Ident,
...
-                                     .map(|ty_bound| {
-            ty_bound.rewrite(context, Shape::legacy(context.config.max_width, indent))
-        })
-                                     .intersperse(Some(" + ".to_string()))
-                                     .collect::<Option<String>>());
+            .map(|ty_bound| {
+                ty_bound.rewrite(context, Shape::legacy(context.config.max_width, indent))
+            })
+            .intersperse(Some(" + ".to_string()))
+            .collect::<Option<String>>());
```
Comment (nrc) [inline src/items.rs]: It looks like this is just a reformatting change. It is nice (though not 100% necessary) to keep reformatting changes in a separate commit because when changing rustfmt there can be lots of them.

File: tests/target/issue_1255.rs [hunk 3]
```diff
@@ -1,8 +0,0 @@
-#![feature(specialization)]
-
-trait Trait {
-    type Type;
-}
-impl<T> Trait for T {
-    default type Type = u64;
-}
```
Comment (nrc) [inline tests/target/issue_1255.rs]: Oh, I see you've made that change here.

So, when structuring the commits in the PR, it is usually best to fix them all up at the end so that they are clearer for a reviewer or person reading commits in the tree, rather than reflecting the evolution of the code as it was written. So, for this PR I would have one commit for the test (squashing in the test changes), one for the changes (squashing the refactoring into the first change), and one for reformatting.

File: src/items.rs [hunk 4]
```diff
@@ -1267,6 +1267,25 @@ pub fn rewrite_associated_type(ident: ast::Ident,
...
+                                    defaultness: ast::Defaultness,
+                                    ty_opt: Option<&ptr::P<ast::Ty>>,
+                                    ty_param_bounds_opt: Option<&ast::TyParamBounds>,
+                                    context: &RewriteContext,
+                                    indent: Indent)
+                                    -> Option<String> {
+    let result = rewrite_associated_type(ident, ty_opt, ty_param_bounds_opt, context, indent);
+
+    if let ast::Defaultness::Default = defaultness {
+        match result {
```
Comment (nrc) [inline src/items.rs]: you could skip this match block by wrapping the rhs of `let result = ...` in `try_opt!`

Comment (nrc) [inline src/items.rs]: and usually `match` is more succinct than `if let ... else` (i.e., I mostly only use `if let` if there is no `else` branch).

**Comment by gypsydave5** [comment]
Thanks for taking the time to give this feedback @nrc, I really appreciate the detail - it'll help me to improve. I should be able to make the code changes quite easily; changing the git history might take a little longer but will be very good practice. Next day or so I reckon.

**Comment by nrc** [comment]
Let me know (perhaps via irc) if you have any Git questions - I know from experience that Git does not make this kind of rebasing simple or intuitive.

**Comment by gypsydave5** [comment]
Well that was fun - splitting commits and then fixing them up again - not done that before. It's now three commits (test, fix and reformat), and I've used `try_opt!` and a `match` instead of the `if... else`.

I won't make quite such a mess of my history next time 😄 !

**Comment by nrc** [comment]
Awesome, thank you!
