### PR TITLE
Single-line Functions

### LINKED ISSUE #262: Support whole functions on one line
Some people like to fit a whole function (decl and body) on one line. They are wrong, but we should support it as an option.

e.g., 

```
pub fn default_options() -> Vec<RenderOption> { vec![] }
```

### PR DESCRIPTION
**Pull request by kyeah**
Fixes #262.

Formats empty-body functions on a single-line if possible, and adds the `fn_single_line` option to do the same for single-statement/expression functions.

Organizational changes:
* `semicolon_for_stmt`, `semicolon_for_expr` moved to utils module; I wasn't sure if these were better suited in the expr module.
* `visit_stmt` logic split off into `impl Rewrite for ast::Stmt`. The visit function still takes care of the logic for visiting/rewriting Items and Macs.

### CODE REVIEW

**Comment by nrc** [comment]
Awesome, thanks for the PR! There should also probably be an option (on by default) for whether we put empty function bodies on one line.

File: tests/target/paths.rs [hunk 1]
```diff
@@ -19,5 +19,4 @@ fn main() {
     let x: Foo<A>;
 }
 
-fn op(foo: Bar, key: &[u8], upd: Fn(Option<&memcache::Item>, Baz) -> Result) -> MapResult {
-}
+fn op(foo: Bar, key: &[u8], upd: Fn(Option<&memcache::Item>, Baz) -> Result) -> MapResult { }
```
Comment (nrc) [inline tests/target/paths.rs]: We should format the function body as `{}` not `{ }`

File: src/visitor.rs [hunk 2]
```diff
@@ -161,6 +154,13 @@ impl<'a> FmtVisitor<'a> {
             visit::FnKind::Closure => None,
         };
 
+        if let Some(ref single_line_fn) = self.rewrite_single_line_fn(&rewrite, &b) {
```
Comment (nrc) [inline src/visitor.rs]: Why do you have a separate `rewrite_single_line_fn` function and this check? I would have though we could just tweak `rewrite_fn` to write an empty block on one line - is that not possible?

File: src/expr.rs [hunk 3]
```diff
@@ -688,6 +716,27 @@ fn is_simple_block(block: &ast::Block, codemap: &CodeMap) -> bool {
...
 
+/// Checks whether a block contains at most one statement or expression, and no comments.
+pub fn is_simple_block_stmt(block: &ast::Block, codemap: &CodeMap) -> bool {
+    if (!block.stmts.is_empty() && block.expr.is_some()) ||
+       (block.stmts.len() != 1 && block.expr.is_none()) {
+        return false;
+    }
+
+    let snippet = codemap.span_to_snippet(block.span).unwrap();
+    !contains_comment(&snippet)
```
Comment (nrc) [inline src/expr.rs]: I feel like we should do some refactoring of the shared code between these functions

File: src/visitor.rs (hunk 2 above)
Comment (kyeah) [inline src/visitor.rs]: Since `rewrite_fn` only handles the function declaration -- not the actual body block -- we'd need to return a bool, or check whether the last character is a closing brace, to know whether to skip `visit_block`. The first solution diverges from the return type of every other `rewrite_X` function, but the second would be fine.

Comment (nrc) [inline src/visitor.rs]: Could we refactor so that rewrite_fn rewrites its own block rather than the visitor doing it?

Comment (kyeah) [inline src/visitor.rs]: It would require a ton of refactoring, since `visit_block` goes down the rabbit hole and offloads a lot of work to `visit_stmt`, `visit_item`, `visit_mac`, etc. A lot of the visitor code would need to be stripped into rewrite functions.

Comment (nrc) [inline src/visitor.rs]: ah ok, that's a shame

**Comment by nrc** [comment]
Thanks for the changes!
