### PR TITLE
Use newline only when fn_call_style is Block

### LINKED ISSUE #1528: comma inserted when formatting long macro
Using rustfmt 0.8.4, a comma is incorrectly inserted after a long string in a panic! macro:

````
fn a() {
    panic!("this is a long string that goes past the maximum line length causing rustfmt to insert a comma here:");
}
````

Result:
````
fn a() {
    panic!("this is a long string that goes past the maximum line length causing rustfmt to insert a comma here:",);
}

````

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #1528 (which I introduced, sorry).

### CODE REVIEW

File: tests/source/configs-fn_call_style-visual.rs [hunk 1]
```diff
@@ -1,6 +1,12 @@
+// rustfmt-error_on_line_overflow: false
```
Comment (nrc) [inline tests/source/configs-fn_call_style-visual.rs]: Could you put the test in a new file please? I fear that adding this config option could allow a test to erroneously pass in the future.

File: src/expr.rs [hunk 2]
```diff
@@ -1779,7 +1779,10 @@ fn rewrite_call_args(context: &RewriteContext,
     };
 
     match write_list(&item_vec, &fmt) {
-        Some(ref s) if !s.contains('\n') && s.len() > one_line_width => {
+        // If arguments do not fit in a single line and do not contain newline,
+        // try to put it on the next line.
+        Some(ref s) if context.config.fn_call_style == IndentStyle::Block &&
+                       (!s.contains('\n') && s.len() > one_line_width) => {
```
Comment (nrc) [inline src/expr.rs]: So while I think this fix is necessary, I don't think it is sufficient - even in block mode, it is a bug to introduce a comma in a macro where there wasn't one before. I think we have a flag which indicates we're formatting a macro rather than a function and we should check that around here some where.

Comment (topecongiro) [inline src/expr.rs]: Thanks for comments! I have 2 questions.
1. Why do we have to distinguish macro and funcation call here? We have the same bug with function call as well.
2. With block mode, I get the following output:
```rust
fn a() {
    panic(
        "this is a long string that goes past the maximum line length causing rustfmt to insert a comma here:",
    );
}
```
That is, rustfmt tries multiline because args don't fit in a single line and hence needs trailing comma, right?

Comment (nrc) [inline src/expr.rs]: 1. with functions, it is not an error to insert commas in general , but with macros it is, e.g.,

```
f(a_long_arg);
// formatted to
f(
    a_long_arg, // OK
);
m!(a_long_arg);
// formatted to
m!(
    a_long_arg, // could introduce a compile error or change semantics
);
```

The underlying reason here is that arguments to macros are not a list of expressions (as they are for functions), but they are a list of tokens, so a macro can potentially 'see' the commas and change behaviour accordingly.

2. This is a bug for macros, if there is not a trailing comma, then we should not add one under any circumstances.

Comment (topecongiro) [inline src/expr.rs]: I see, thanks!

**Comment by topecongiro** [comment]
Rebased with suggested changes.
