### PR TITLE
Change format_snippet to return None when it has failed to format macro call

### LINKED ISSUE #2607: Rustfmt Unconditionally Indents Code Each Time It's Run
This is an odd bug I found while running rustfmt on Criterion.rs.

Steps to reproduce:
* `cargo init rustfmt-test`
* Create a benches directory (this doesn't happen if the code is in src)
* Create a file named `test.rs` in the benches directory with the following code:
```rust
macro_rules! bench {
    ($ty:ident) => {
        criterion_group!(
            name = benches;
            config = ::common_bench::reduced_samples();
            targets = call, map;
        );
    };
}
```
* Run `cargo +nightly fmt`. Code now looks like this:
```rust
macro_rules! bench {
    ($ty:ident) => {
        criterion_group!(
                    name = benches;
                    config = ::common_bench::reduced_samples();
                    targets = call, map;
                );
    };
}
```
* Run `cargo +nightly fmt` again. Code now looks like this:
```rust
macro_rules! bench {
    ($ty:ident) => {
        criterion_group!(
                            name = benches;
                            config = ::common_bench::reduced_samples();
                            targets = call, map;
                        );
    };
}
```

It always adds another 8 spaces before those four lines. I haven't been able to find a workaround for this (though if you find one, please let me know so I can re-enable my rustfmt Travis-CI build).

### LINKED ISSUE #2770: Weird formatting of asm! statement within macro definition
Niche use-case maybe, but this is what the current nightly `rustfmt` (`rustfmt 0.8.2-nightly (173ae0d 2018-05-28)`) produces:
``` rust
macro_rules! save_regs {
    () => {
        asm!("push rax
              push rcx
              push rdx
              push rsi
              push rdi
              push r8
              push r9
              push r10
              push r11"
                                     :::: "intel", "volatile");
    };
}
```

Specifically, the indentation before the colons seems excessive?

### PR DESCRIPTION
**Pull request by topecongiro**
rustfmt manually adds/removes indentation when trying to format macro def's body. This does not work when the macro body contains a macro call that rustfmt cannot format, and causes an issue like #2607 or #2770. This PR fixes it by changing the `format_snippet` to return `None` when it has failed to format the macro call in the snippet.

Closes #2607.
Closes #2770.

### CODE REVIEW

**Comment by nrc** [comment]
There's a few test failures, but r+ with those fixed

**Comment by topecongiro** [comment]
Thank you for you review! I have fixed the test failures.

N.B. rustfmt is now unable to format code block with invalid syntax macro calls, like the one in tests/target/issue-2523.rs.

File: src/lib.rs [hunk 1]
```diff
@@ -422,13 +422,14 @@ fn format_ast<F>(
...
     mut after_file: F,
-) -> Result<(FileMap, bool), io::Error>
+) -> Result<(FileMap, bool, bool), io::Error>
 where
     F: FnMut(&FileName, &mut String, &[(usize, usize)], &FormatReport) -> Result<bool, io::Error>,
 {
     let mut result = FileMap::new();
     // diff mode: check if any files are differing
     let mut has_diff = false;
+    let mut has_macro_rewrite_failure = false;
```
Comment (thibaultdelor) [inline src/lib.rs]: @topecongiro @nrc 
Shouldn't `has_macro_rewrite_failure` be part of the `FormatReport` instead?
IMO That should be a new ErrorKind

Comment (nrc) [reply src/lib.rs]: I figure the two will get merged in some way, so it doesn't really matter what we do right now
