### PR TITLE
Fix #977

### LINKED ISSUE #977: Bad formatting for items with just a single comment
```rust
trait NameC { /* comment */ }
struct FooC { /* comment */ }
enum MooC { /* comment */ }
mod BarC { /* comment */ }
extern { /* comment */ }
```
Is formatted to (notice that the struct is not formatted, enum's `}` has bad indent and extern's `{` has disappeared):
```rust
trait NameC {
    // comment
}
struct FooC { /* comment */ }
enum MooC {
    // comment
 }
mod BarC {
    // comment
}
extern "C" 
// comment
}
```

Also this error is thrown:
```
Rustfmt failed at moo.rs:11: left behind trailing whitespace (sorry)
```

rustfmt 0.4.1

### PR DESCRIPTION
**Pull request by sinkuu**
#977

Maybe we need to format all blocks with a single block-comment like #919, but at least the garbage space before `enum`'s `}` and the missing `{` of `extern` are fixed.

### CODE REVIEW

File: src/missed_spans.rs [hunk 1]
```diff
@@ -34,6 +34,12 @@ impl<'a> FmtVisitor<'a> {
         })
     }
 
+    pub fn format_missing_comments(&mut self, end: BytePos) {
+        self.format_missing_inner(end, |_, _, _| {
+            // do nothing
```
Comment (nrc) [inline src/missed_spans.rs]: this will just drop the last snippet on the floor, why is that OK?

Comment (sinkuu) [inline src/missed_spans.rs]: Because this is called where only comments or white spaces exist. I updated to do `this.buffer.push_str(last_snippet.trim_right());` since I just wanted a version of `format_missing_indent` that doesn't insert indents.

**Comment by nrc** [comment]
Thank you!
