### PR TITLE
More fine-grained file-lines

### LINKED ISSUE #1835: --file-lines (range formatting) seems to be broken in a couple of ways
Hey -- I'm trying to integrate RLS and rustfmt with our IDE, and it looks like range formatting is broken in a couple of ways. Here's a repro with 19bd5ea7b3feafe3eac1b6a033ca6db44d40ab32, with these settings:

```
condense_wildcard_suffixes = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
```

1. Download `lz4.rs` from [this gist](https://gist.github.com/sid0/4164a202cc976b0b48f76ad4c706ad29) somewhere.
2. `rustfmt lz4.rs --file-lines '[{"file": "lz4.rs", "range": [20, 27]}]' --write-mode display`
3. What you get back looks like `lz4_output.rs`.

Note a couple of things:

1. Imports were reordered even though none of the imports were in the range.
2. Line 32 got formatted even though it isn't in the range.

### PR DESCRIPTION
**Pull request by topecongiro**
Currently rustfmt ignores file lines check for items.
Closes #1835.

### CODE REVIEW

File: src/visitor.rs [hunk 1]
```diff
@@ -60,21 +60,20 @@ pub struct FmtVisitor<'a> {
 }
 
 impl<'a> FmtVisitor<'a> {
+    // Return true if the given span does not intersect with file lines.
+    fn skip_span(&self, span: Span) -> bool {
```
Comment (nrc) [inline src/visitor.rs]: Can we use the context version of `skip_span` rather than duplicating the code?

File: src/visitor.rs [hunk 2]
```diff
@@ -264,6 +263,10 @@ impl<'a> FmtVisitor<'a> {
     }
 
     pub fn visit_item(&mut self, item: &ast::Item) {
+        if self.skip_span(item.span) {
+            return;
+        }
```
Comment (nrc) [inline src/visitor.rs]: We could make this a macro and wouldn't have to repeat the `if ... return`.

File: src/visitor.rs (hunk 1 above)
Comment (topecongiro) [inline src/visitor.rs]: We could, though we need to call `get_context()` everytime, which is a bit unfortunate.

**Comment by topecongiro** [comment]
Rebased with the change to use macro.

**Comment by emilio** [comment]
I was super-excited to try this with bindgen, but this causes a bunch of undesired effects.

Current STR (will try to find something more reduced later today):

 * Clone https://github.com/rust-lang-nursery/rust-bindgen.
 * Apply this diff (for example):

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 3a85382..1b68a0a 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1268,7 +1268,7 @@ fn filter_builtins(ctx: &BindgenContext, cursor: &clang::Cursor) -> bool {
 
 /// Parse one `Item` from the Clang cursor.
 pub fn parse_one(ctx: &mut BindgenContext,
-                 cursor: clang::Cursor,
+             cursor: clang::Cursor,
                  parent: Option<ItemId>)
                  -> clang_sys::CXChildVisitResult {
     if !filter_builtins(ctx, &cursor) {
```

 * Run [rustfmt-format-diff.py](https://github.com/emilio/rustfmt-format-diff/), which as of right now it does:

```shell
rustfmt --file-lines '[{"range": [1268, 1274], "file": "src/lib.rs"}]' src/lib.rs
```

Expected: Only the `parse_one` signature is modified.

Actual: A lot of use statements and whitespace is missing, and also lines with comments misindented.

**Comment by emilio** [comment]
This helps not to get them skipped, but the use statements still get reformatted / reordered:

```
diff --git a/src/utils.rs b/src/utils.rs
index 9c1717e..47ce5e7 100644
--- a/src/utils.rs
+++ b/src/utils.rs
@@ -343,6 +343,7 @@ macro_rules! skip_out_of_file_lines_range {
 macro_rules! skip_out_of_file_lines_range_visitor {
     ($self:ident, $span:expr) => {
         if out_of_file_lines_range!($self, $span) {
+            $self.push_rewrite($span, None);
             return;
         }
     }
```

Disclaimer, no clue about whether it's the right fix :-)

**Comment by emilio** [comment]
Ok, I also got a patch for the other issue, I'll try to add some tests :-)

**Comment by emilio** [comment]
I opened #1841 with my fixes on top of this.

Also, thanks @topecongiro! I was about to report too much stuff being formated with file-lines, and you already had a fix up for review, that's awesome! :)

**Comment by nrc** [comment]
Thanks for the changes!
